import { TRPCReactProvider } from '@/trpc/client'
import { Provider as JotaiProvider } from 'jotai'
import { BadgeAlertIcon, BadgeCheckIcon, BadgeXIcon } from 'lucide-react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Toaster } from 'sonner'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCReactProvider>
          <NuqsAdapter>
            <JotaiProvider>
              {children}

              <Toaster
                closeButton
                swipeDirections={['bottom', 'right']}
                icons={{
                  success: <BadgeCheckIcon className="text-emerald-500" />,
                  error: <BadgeXIcon className="text-red-500" />,
                  warning: <BadgeAlertIcon className="text-yellow-600" />,
                }}
              />
            </JotaiProvider>
          </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
